#define RADAR_NODRAW			0
#define RADAR_FRIEND			1
#define RADAR_ENEMY				2
#define RADAR_MARK				3
#define RADAR_OBJECT			4
#define RADAR_TERMINAL			5
#define RADAR_TERMINAL_HACKED	6
#define RADAR_BLINK				7
#define RADAR_BLINK_TEMP		8

// 0x0001 - 0x0059: MidScreen notify
#define NTM_HUMAN_ESC 0x0001
#define NTM_TIMEUP 0x0002
#define NTM_ALLDEAD 0x0003
#define NTM_DRAW 0x0004
#define NTM_ZOMBIE 0x0005
#define NTM_HUMAN 0x0006
#define NTM_MISSION 0x0007


#ifndef MISSION_RESCUE
#define MISSION_RESCUE 1
#define MISSION_FRAGS 10
#define MISSION_FRED 11
#define MISSION_OBJECT 12
#define MISSION_CUSTOM 80
#endif

#define NTM_MISSION_START (0x0008)
#define NTM_MISSION_RESCUE (NTM_MISSION_START+MISSION_RESCUE)
#define NTM_MISSION_FRAGS (NTM_MISSION_START+MISSION_FRAGS)
#define NTM_MISSION_FRED (NTM_MISSION_START+MISSION_FRED)
#define NTM_MISSION_OBJECT (NTM_MISSION_START+MISSION_OBJECT)

#define NTM_MISSION_OBJECT (NTM_MISSION_START+MISSION_OBJECT)

#define NTM_OBJECTRESTORE 0x0016

#define NTM_REHUMAN 0x0017
#define NTM_DONE_ZOMBIE 0x0018
#define NTM_DONE_SPECTATE 0x0019

#define NTM_CUSTOM 0x0020

// 0x0060 - 0x0079: Not displayed
#define NTM_REHUMAN_HIDE 0x0060
#define NTM_DONE_HIDE 0x0062

// 0x0080+ : TopLeft notify
#define NTC_ZOMBIE 0x0080
#define NTC_HUMAN 0x0081


#define NTC_MISSION_START (0x0082)
#define NTC_MISSION_RESCUE (NTC_MISSION_START+MISSION_RESCUE)
#define NTC_MISSION_FRAGS (NTC_MISSION_START+MISSION_FRAGS)
#define NTC_MISSION_FRED (NTC_MISSION_START+MISSION_FRED)
#define NTC_MISSION_OBJECT (NTC_MISSION_START+MISSION_OBJECT)

#define NTC_CUSTOM 0x0090



